// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PieShop.Data;

namespace PieShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200628221114_AddedOrder")]
    partial class AddedOrder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PieShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Ciasto owocowe"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Sernik"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "sezonowe ciasta"
                        });
                });

            modelBuilder.Entity("PieShop.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("PieShop.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PieId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PieId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("PieShop.Models.Pie", b =>
                {
                    b.Property<int>("PieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllergyInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPieOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pies");

                    b.HasData(
                        new
                        {
                            PieId = 1,
                            AllergyInformation = "",
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "Lodowaty placek z galaretki o-marchewkowy. Słodka bułka marcepan marshmallow toffi brownie brownie cukierek tootsie roll. Ciasto czekoladowe piernik tootsie bułka owsiane ciasto ciasto czekoladowe ciasteczko ciastko dragée brownie. Lollipop wata cukrowa ciasto niedźwiedź pazur owies ciasto. Dragée cukierki laski deserowe tarta. Marcepan żelki dragée lizak jujuby batoniki czekoladowe laski. lukier piernik chupa chups wata cukrowa ciasteczko słodki lukier żelki żelki żelki żelki ciasteczko duńskie ciastko czekoladowe duńskie ciastko w proszku makaronik czekoladowy pączek tarta ciasto marchewkowe drób rogalik krople cytryny lukrecja krople cytryny ciastko lollipop toffi. Ciasto marchewkowe Ciasto marchewkowe Lukrecja Cukier Śliwka Polewa Bonbon Pie Muffin Jujubes. Galaretka Ciasto Waflowe Tarta Karmel Niedźwiedź Pazur. Tiramisu Tarta Ciasto Duńskie Krople Cytryny. Brownie Babeczka Dragée żelki. ",
                            Name = "Szarlotka",
                            Price = 12.95m,
                            ShortDescription = "Nasze słynne szarlotki!"
                        },
                        new
                        {
                            PieId = 2,
                            AllergyInformation = "",
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/blueberrycheesecakesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/blueberrycheesecake.jpg",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "Lodowaty placek z galaretki o-marchewkowy. Słodka bułka marcepan marshmallow toffi brownie brownie cukierek tootsie roll. Ciasto czekoladowe piernik tootsie bułka owsiane ciasto ciasto czekoladowe ciasteczko ciastko dragée brownie. Lollipop wata cukrowa ciasto niedźwiedź pazur owies ciasto. Dragée cukierki laski deserowe tarta. Marcepan żelki dragée lizak jujuby batoniki czekoladowe laski. lukier piernik chupa chups wata cukrowa ciasteczko słodki lukier żelki żelki żelki żelki ciasteczko duńskie ciastko czekoladowe duńskie ciastko w proszku makaronik czekoladowy pączek tarta ciasto marchewkowe drób rogalik krople cytryny lukrecja krople cytryny ciastko lollipop toffi. Ciasto marchewkowe Ciasto marchewkowe Lukrecja Cukier Śliwka Polewa Bonbon Pie Muffin Jujubes. Galaretka Ciasto Waflowe Tarta Karmel Niedźwiedź Pazur. Tiramisu Tarta Ciasto Duńskie Krople Cytryny. Brownie Babeczka Dragée żelki. ",
                            Name = "Sernik jagodowy",
                            Price = 18.95m,
                            ShortDescription = "Pokochasz to!"
                        },
                        new
                        {
                            PieId = 3,
                            AllergyInformation = "",
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cheesecakesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cheesecake.jpg",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "Lukierowy żelkowy tort żelowy sernik. Słodka bułka marcepan marshmallow toffi brownie brownie tootsie roll. Ciasto Czekoladowe Piernik Tootsie Roll Owies Ciasto Ciasto Czekoladowe Ciastko Dragée Brownie. Lollipop Wata cukrowa ciasto niedźwiedź pazur owsiane ciasto. Tarta deserowa z trzciny cukrowej Dragée. Marcepanowe dragée żelki lizakowe jujuby batoniki czekoladowe. Lukier chupa chupa chups wata cukrowa ciasteczko słodki lukier bonbonowe żelki. Gummies Lollipop Brownie Biscuit Duńskie Ciasto Czekoladowe. Ciastko w proszku duński makaronik czekoladowy pączek. Ciasto marchewkowe Dragée Rogalik Krople cytryny Lukrecja Krople cytryny Ciastko Lollipop Toffi. Ciasto marchewkowe Ciasto marchewkowe Lukrecja Cukier Śliwka Polewa Bonbon Pie Muffin Jujubes. Tarta waflowa karmelowa tarta karmelowa niedźwiedź pazur. Ciasto tarta tiramisu duńskie krople cytryny. Babeczki Brownie Dragée.",
                            Name = "Sernik",
                            Price = 18.95m,
                            ShortDescription = "Zwykły sernik. Zwykła przyjemność."
                        },
                        new
                        {
                            PieId = 4,
                            AllergyInformation = "",
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherrypiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherrypie.jpg",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "Lukierowy żelkowy tort żelowy sernik. Słodka bułka marcepan marshmallow toffi brownie brownie tootsie roll. Ciasto Czekoladowe Piernik Tootsie Roll Owies Ciasto Ciasto Czekoladowe Ciastko Dragée Brownie. Lollipop Wata cukrowa ciasto niedźwiedź pazur owsiane ciasto. Tarta deserowa z trzciny cukrowej Dragée. Marcepanowe dragée żelki lizakowe jujuby batoniki czekoladowe. Lukier chupa chupa chups wata cukrowa ciasteczko słodki lukier bonbonowe żelki. Gummies Lollipop Brownie Biscuit Duńskie Ciasto Czekoladowe. Ciastko w proszku duński makaronik czekoladowy pączek. Ciasto marchewkowe Dragée Rogalik Krople cytryny Lukrecja Krople cytryny Ciastko Lollipop Toffi. Ciasto marchewkowe Ciasto marchewkowe Lukrecja Cukier Śliwka Polewa Bonbon Pie Muffin Jujubes. Tarta waflowa karmelowa tarta karmelowa niedźwiedź pazur. Ciasto tarta tiramisu duńskie krople cytryny. Babeczki Brownie Dragée.",
                            Name = "Placek wiśniowy",
                            Price = 15.95m,
                            ShortDescription = "Letni klasyk!"
                        },
                        new
                        {
                            PieId = 5,
                            AllergyInformation = "",
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplepiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplepie.jpg",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "Lukierowy żelkowy tort żelowy sernik. Słodka bułka marcepan marshmallow toffi brownie brownie tootsie roll. Ciasto Czekoladowe Piernik Tootsie Roll Owies Ciasto Ciasto Czekoladowe Ciastko Dragée Brownie. Lollipop Wata cukrowa ciasto niedźwiedź pazur owsiane ciasto. Tarta deserowa z trzciny cukrowej Dragée. Marcepanowe dragée żelki lizakowe jujuby batoniki czekoladowe. Lukier chupa chupa chups wata cukrowa ciasteczko słodki lukier bonbonowe żelki. Gummies Lollipop Brownie Biscuit Duńskie Ciasto Czekoladowe. Ciastko w proszku duński makaronik czekoladowy pączek. Ciasto marchewkowe Dragée Rogalik Krople cytryny Lukrecja Krople cytryny Ciastko Lollipop Toffi. Ciasto marchewkowe Ciasto marchewkowe Lukrecja Cukier Śliwka Polewa Bonbon Pie Muffin Jujubes. Tarta waflowa karmelowa tarta karmelowa niedźwiedź pazur. Ciasto tarta tiramisu duńskie krople cytryny. Babeczki Brownie Dragée.",
                            Name = "Świąteczna Szarlotka",
                            Price = 13.95m,
                            ShortDescription = "Wesołych świąt z tym ciastem!"
                        },
                        new
                        {
                            PieId = 6,
                            AllergyInformation = "",
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberrypiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberrypie.jpg",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "Lukierowy żelkowy tort żelowy sernik. Słodka bułka marcepan marshmallow toffi brownie brownie tootsie roll. Ciasto Czekoladowe Piernik Tootsie Roll Owies Ciasto Ciasto Czekoladowe Ciastko Dragée Brownie. Lollipop Wata cukrowa ciasto niedźwiedź pazur owsiane ciasto. Tarta deserowa z trzciny cukrowej Dragée. Marcepanowe dragée żelki lizakowe jujuby batoniki czekoladowe. Lukier chupa chupa chups wata cukrowa ciasteczko słodki lukier bonbonowe żelki. Gummies Lollipop Brownie Biscuit Duńskie Ciasto Czekoladowe. Ciastko w proszku duński makaronik czekoladowy pączek. Ciasto marchewkowe Dragée Rogalik Krople cytryny Lukrecja Krople cytryny Ciastko Lollipop Toffi. Ciasto marchewkowe Ciasto marchewkowe Lukrecja Cukier Śliwka Polewa Bonbon Pie Muffin Jujubes. Tarta waflowa karmelowa tarta karmelowa niedźwiedź pazur. Ciasto tarta tiramisu duńskie krople cytryny. Babeczki Brownie Dragée.",
                            Name = "Ciasto żurawinowe",
                            Price = 17.95m,
                            ShortDescription = "Ulubiony na święta"
                        },
                        new
                        {
                            PieId = 7,
                            AllergyInformation = "",
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachpiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachpie.jpg",
                            InStock = false,
                            IsPieOfTheWeek = false,
                            LongDescription = "Lukierowy żelkowy tort żelowy sernik. Słodka bułka marcepan marshmallow toffi brownie brownie tootsie roll. Ciasto Czekoladowe Piernik Tootsie Roll Owies Ciasto Ciasto Czekoladowe Ciastko Dragée Brownie. Lollipop Wata cukrowa ciasto niedźwiedź pazur owsiane ciasto. Tarta deserowa z trzciny cukrowej Dragée. Marcepanowe dragée żelki lizakowe jujuby batoniki czekoladowe. Lukier chupa chupa chups wata cukrowa ciasteczko słodki lukier bonbonowe żelki. Gummies Lollipop Brownie Biscuit Duńskie Ciasto Czekoladowe. Ciastko w proszku duński makaronik czekoladowy pączek. Ciasto marchewkowe Dragée Rogalik Krople cytryny Lukrecja Krople cytryny Ciastko Lollipop Toffi. Ciasto marchewkowe Ciasto marchewkowe Lukrecja Cukier Śliwka Polewa Bonbon Pie Muffin Jujubes. Tarta waflowa karmelowa tarta karmelowa niedźwiedź pazur. Ciasto tarta tiramisu duńskie krople cytryny. Babeczki Brownie Dragée.",
                            Name = "Ciasto brzoskwiniowe",
                            Price = 15.95m,
                            ShortDescription = "Słodka jak brzoskwinia"
                        },
                        new
                        {
                            PieId = 8,
                            AllergyInformation = "",
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinpiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinpie.jpg",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "Lukierowy żelkowy tort żelowy sernik. Słodka bułka marcepan marshmallow toffi brownie brownie tootsie roll. Ciasto Czekoladowe Piernik Tootsie Roll Owies Ciasto Ciasto Czekoladowe Ciastko Dragée Brownie. Lollipop Wata cukrowa ciasto niedźwiedź pazur owsiane ciasto. Tarta deserowa z trzciny cukrowej Dragée. Marcepanowe dragée żelki lizakowe jujuby batoniki czekoladowe. Lukier chupa chupa chups wata cukrowa ciasteczko słodki lukier bonbonowe żelki. Gummies Lollipop Brownie Biscuit Duńskie Ciasto Czekoladowe. Ciastko w proszku duński makaronik czekoladowy pączek. Ciasto marchewkowe Dragée Rogalik Krople cytryny Lukrecja Krople cytryny Ciastko Lollipop Toffi. Ciasto marchewkowe Ciasto marchewkowe Lukrecja Cukier Śliwka Polewa Bonbon Pie Muffin Jujubes. Tarta waflowa karmelowa tarta karmelowa niedźwiedź pazur. Ciasto tarta tiramisu duńskie krople cytryny. Babeczki Brownie Dragée.",
                            Name = "Ciasto dyniowe",
                            Price = 12.95m,
                            ShortDescription = "Nasz ulubiony Halloween"
                        },
                        new
                        {
                            PieId = 9,
                            AllergyInformation = "",
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbpiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbpie.jpg",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "Lukierowy żelkowy tort żelowy sernik. Słodka bułka marcepan marshmallow toffi brownie brownie tootsie roll. Ciasto Czekoladowe Piernik Tootsie Roll Owies Ciasto Ciasto Czekoladowe Ciastko Dragée Brownie. Lollipop Wata cukrowa ciasto niedźwiedź pazur owsiane ciasto. Tarta deserowa z trzciny cukrowej Dragée. Marcepanowe dragée żelki lizakowe jujuby batoniki czekoladowe. Lukier chupa chupa chups wata cukrowa ciasteczko słodki lukier bonbonowe żelki. Gummies Lollipop Brownie Biscuit Duńskie Ciasto Czekoladowe. Ciastko w proszku duński makaronik czekoladowy pączek. Ciasto marchewkowe Dragée Rogalik Krople cytryny Lukrecja Krople cytryny Ciastko Lollipop Toffi. Ciasto marchewkowe Ciasto marchewkowe Lukrecja Cukier Śliwka Polewa Bonbon Pie Muffin Jujubes. Tarta waflowa karmelowa tarta karmelowa niedźwiedź pazur. Ciasto tarta tiramisu duńskie krople cytryny. Babeczki Brownie Dragée.",
                            Name = "ciasto rabarbarowe",
                            Price = 15.95m,
                            ShortDescription = "Mój Boże, taki słodki!"
                        },
                        new
                        {
                            PieId = 10,
                            AllergyInformation = "",
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrypiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrypie.jpg",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "Lukierowy żelkowy tort żelowy sernik. Słodka bułka marcepan marshmallow toffi brownie brownie tootsie roll. Ciasto Czekoladowe Piernik Tootsie Roll Owies Ciasto Ciasto Czekoladowe Ciastko Dragée Brownie. Lollipop Wata cukrowa ciasto niedźwiedź pazur owsiane ciasto. Tarta deserowa z trzciny cukrowej Dragée. Marcepanowe dragée żelki lizakowe jujuby batoniki czekoladowe. Lukier chupa chupa chups wata cukrowa ciasteczko słodki lukier bonbonowe żelki. Gummies Lollipop Brownie Biscuit Duńskie Ciasto Czekoladowe. Ciastko w proszku duński makaronik czekoladowy pączek. Ciasto marchewkowe Dragée Rogalik Krople cytryny Lukrecja Krople cytryny Ciastko Lollipop Toffi. Ciasto marchewkowe Ciasto marchewkowe Lukrecja Cukier Śliwka Polewa Bonbon Pie Muffin Jujubes. Tarta waflowa karmelowa tarta karmelowa niedźwiedź pazur. Ciasto tarta tiramisu duńskie krople cytryny. Babeczki Brownie Dragée.",
                            Name = "Ciasto truskawkowe",
                            Price = 15.95m,
                            ShortDescription = "Nasze pyszne ciasto truskawkowe!"
                        },
                        new
                        {
                            PieId = 11,
                            AllergyInformation = "",
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrycheesecakesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrycheesecake.jpg",
                            InStock = false,
                            IsPieOfTheWeek = false,
                            LongDescription = "Lukierowy żelkowy tort żelowy sernik. Słodka bułka marcepan marshmallow toffi brownie brownie tootsie roll. Ciasto Czekoladowe Piernik Tootsie Roll Owies Ciasto Ciasto Czekoladowe Ciastko Dragée Brownie. Lollipop Wata cukrowa ciasto niedźwiedź pazur owsiane ciasto. Tarta deserowa z trzciny cukrowej Dragée. Marcepanowe dragée żelki lizakowe jujuby batoniki czekoladowe. Lukier chupa chupa chups wata cukrowa ciasteczko słodki lukier bonbonowe żelki. Gummies Lollipop Brownie Biscuit Duńskie Ciasto Czekoladowe. Ciastko w proszku duński makaronik czekoladowy pączek. Ciasto marchewkowe Dragée Rogalik Krople cytryny Lukrecja Krople cytryny Ciastko Lollipop Toffi. Ciasto marchewkowe Ciasto marchewkowe Lukrecja Cukier Śliwka Polewa Bonbon Pie Muffin Jujubes. Tarta waflowa karmelowa tarta karmelowa niedźwiedź pazur. Ciasto tarta tiramisu duńskie krople cytryny. Babeczki Brownie Dragée.",
                            Name = "Sernik truskawkowy",
                            Price = 18.95m,
                            ShortDescription = "Pokochasz to!"
                        });
                });

            modelBuilder.Entity("PieShop.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("PieId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("PieId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("PieShop.Models.OrderDetail", b =>
                {
                    b.HasOne("PieShop.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PieShop.Models.Pie", "Pie")
                        .WithMany()
                        .HasForeignKey("PieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PieShop.Models.Pie", b =>
                {
                    b.HasOne("PieShop.Models.Category", "Category")
                        .WithMany("Pies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PieShop.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("PieShop.Models.Pie", "Pie")
                        .WithMany()
                        .HasForeignKey("PieId");
                });
#pragma warning restore 612, 618
        }
    }
}
